### ISSUE TITLE
cannot read properties of undefined (reading 'digest') for Windows Binary Release v1.3.5 and above

### ISSUE THREAD

**Issue by notcasper00** [NUWCDIVNPT/stig-manager#1034]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of STIG Manager?

- [X] I am using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases).
- [ ] I am NOT using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases). I am aware that the first thing I will be asked to do is update the application so that I have the latest bugfixes.

### Where are you experiencing the issue?

- [X] API
- [X] UI or other client
- [X] Deployment
- [ ] Elsewhere

### Current Behavior

When upgrading from v.1.3.4 (last know version that works) to any newer releases up to v.1.3.8. Hitting the STIG Manager web URL will load and display the following error message:
**cannot read properties of undefined (reading 'digest')**

Upon error, I tried to swap the binary release back to the known working version and was able to reproduce the issue. 

### Expected Behavior

Visiting the STIG Manager URL directly on the port, should load the login page to STIG Manager.

### Can you provide screenshots, logs, or other useful artifacts?

Unable to provide any logs or screenshots from an air-gapped network. 

### Describe your Environment

```markdown
- Hosting: Self hosted
- Browser: Lastest Chrome and Edge browsers
- OS: Server 2019
- Node: N/A (Windows Binary)
- npm: N/A
- MySQL: Latest current version
```

**Comment by cd-rite** [comment]
Hi @notcasper00 Releases past 1.3.5 require a Secure Context in order to operate [(See Release Notes for 1.3.5) ](https://github.com/NUWCDIVNPT/stig-manager/releases/tag/1.3.5)

"This change uses features of the browser that require the web client to be in a [Secure Context](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts). A Secure Context is one that is either using HTTPS with a valid certificate or is from localhost."

I'm guessing you've deployed STIGMan with a self-signed cert, or another cert that your browser does not know about. You could import that cert into your browser/system wherever you want to access STIGMan from, or deploy STIGMan with a valid cert derived from a CA available to your browser.
More info available in the "secure context" link above.
