### ISSUE TITLE
FEATURE REQUEST: Implement support to upload .cklb files

### ISSUE THREAD

**Issue by vogtjob** [NUWCDIVNPT/stig-manager#1050]
**Is your feature request related to a problem? Please describe.**
DISA has recently released STIG Viewer 3.  When saving checklists they are saved in a new format (.cklb).  For whatever reason, the new STIG Viewer tool does not seem to allow saving checklists in the .ckl format.

**Describe the solution you'd like**
Ability to upload .cklb files generated by STIG Viewer 3.

**Describe alternatives you've considered**
N/A

**Additional context**
https://public.cyber.mil/stigs/srg-stig-tools/
https://dl.dod.cyber.mil/wp-content/uploads/stigs/pdf/U_STIG_Viewer_3-x_User_Guide_V1R1.pdf

**Comment by cd-rite** [comment]
Hi @vogtjob 
We have heard this news, and do intend to add support for import/export in that new .cklb format. Unfortunately, DISA has provided no supporting resources about this new format.  We also have no idea if other .ckl-consuming systems, like eMASS support it.

I've emailed DISA with some questions, like:
**Do you offer any developer resources or a JSON schema that could be used for validation of the new .cklb format?
Is the format extensible so that tooling can insert its own metadata?
.cklb seems to be called a "Beta Checklist" when saving. Does that imply the format or standard is not yet stable and will be subject to change in the future?
Is eMASS is able to support .cklb format yet?**

Unfortunately, I've received no response from them. We are encouraging other users of their tools to ask these questions too. Perhaps if they get enough questions they will publish some more useful info about the new format, and perhaps provide more public warning of format changes like this in the future.
Their support email address is: disa.stig_spt@mail.mil
Thanks!

**Comment by vogtjob** [comment]
Thanks for looking into it. Our organization will be sure to email a list of questions as well.  Thank you,
