### ISSUE TITLE
Inconsistent terminology "stig assignment" vs "stig attachment"

### ISSUE THREAD

**Issue by cd-rite** [NUWCDIVNPT/stig-manager#118]
We use slightly inconsistent terminology in some areas of the app and documentation.

UI: Asset Properties popup -  "STIG Attachments" labeled "STIG Assignments"

**Comment by csmig** [comment]
What is the consensus for the preferred ontology/terminology? A change here has impact on the API spec and method names as well, so I'm going to hold off until more stakeholders have weighed in.

To further muddle this, is there any interest in using the terms "STIG mappings" and "mapped Assets". Also, please note that "Attachments" might be problematic because of a possible future feature that supports attaching artifacts to Reviews.

Naming is definitely one of the hard problems in computer science!

**Comment by cd-rite** [comment]
Let's go with "Assign."  It's the term I hear used most used by users for this concept, and is already used in some places in UI/API.

Assets get assigned STIGs
and 
STIGs are assigned to assets
