### ISSUE TITLE
FEATURE REQUEST: Add Eval-STIG version element to Asset view tab.

### ISSUE THREAD

**Issue by bbcallison** [NUWCDIVNPT/stig-manager#1191]
**Is your feature request related to a problem? Please describe.**

For those utilizing the Eval-STIG tool, one of the most important STIG QA checks is to ensure assets are utilizing the latest STIG version in their latest STIGMAN  submissions to gain all the new stig automation, bug fixes, etc.  Our team has deadline for STIG submissions and will create incident tickets where admins are not utilizing the latest Eval-STIG version for their STIG submissions. 

Our site will sample a STIG collection, usually the OS STIG, to export out the 'Detail' field data to a CSV so we can have all the 'Evaluate-STIG X.XXXX.X.X (example Evaluate-STIG 1.2301.0 ) version info.  We will then use excel filters to look for "Does Not Contain' and use the latest version to get a list of ALL assets that are not using the latest the latest version and submit ticket to SME's to resubmit.  Being able to quickly filter for this within the STIGMAN tool would be very helpful to remove all the additional export and excel steps to get that info.

**Describe the solution you'd like**
2 possible solutions that would work for me.
1 ) options to filter on the 'Detail' field and be able to search for a specific text string (e.g., Show assets where 'Detail'  does not equal "Evaluate-STIG 1.2301.0" 
2) with the <Evaluate-STIG> element in the CKL being passed along to STIGMAN for the review, map that into a new 'Eval-STIG version' field on the Asset list view.  Have it contain the latest Eval-STIG version # it has seen within the collection. 

Either option would work but my preference would be #2.

**Describe alternatives you've considered**

Export the entire collection to CSV, use excel filtering to look for a string of data, etc.  Would prefer to stay inside the tool and look at all assets as a whole.  

**Additional context**

**Comment by cd-rite** [comment]
Hi @bbcallison Thanks for submitting this issue!
Are you referring to the list of Assets in the Collection Review Workspace for particular STIGs?
When you say you export the entire collection to CSV, do you do that for each Rule, or just a sample one and assume they all used the same tool?
We actually do offer the ability to filter on the Details field in that view (Most columns in most of our grids are filterable):
![image](https://github.com/NUWCDIVNPT/stig-manager/assets/61710958/2535bdbc-5f78-49b0-adf0-be97e1300762)

Is that what you are looking for with Solution 1?  Or are you looking for an "exclude" filter?

We also support a distinct "ResultEngine" field attached to every Review that could facilitate this, rather than having to look in the Detail text. It records the tool/product used to create the automated evaluation, and could potentially be exposed in that view. It also includes additional info about the module and (soon) module version Eval-STIG used for the evaluation. 
I think the module and module version may actually be more important for your purposes, since the individual STIG modules are often updated individually without a corresponding Eval-STIG update. 
For example, the Eval-STIG instance running a module could be at version 1.2310.1
But the module used for evaluation could be:
Scan-GoogleChrome_Checks:1.2023.7.24

We may be able to add this as an optional column to that view, to let you directly filter/exclude certain ResultEngine and/or module values....

**Comment by dtester1** [comment]
Those options listed sounds like good thoughts.  I see the version of evaluate-stig really coming in when you are trying to trobleshoot if the check is reflecting correctly and whether you are using the latest or not that might have bug fixes in later version.

**Comment by cd-rite** [comment]
We've added this data to the metrics export, and will reopen/recreate issue if needed
