### ISSUE TITLE
Upgrade STIG Manager server

### ISSUE THREAD

**Issue by AkashiyaWolf** [NUWCDIVNPT/stig-manager#1216]
Is there documentation on how to upgrade a STIG Manager server while preserving my data?

**Comment by cd-rite** [comment]
Hi @AkashiyaWolf 
Hmmm... I guess there isn't! I'll try to add a section to our Docs about it for the next release. 

However, it should be pretty easy because the STIG Manager API itself is stateless.   All data is stored in the external MySQL database that is provided to STIG Manager as a resource. So preserving the data is up to the deployment admins!

- If you are running the binaries, just stop the old one and start the new one with the same configuration.

- If you are running the STIGMan API as a container, you could just stop the current one, pull the new image, and start the new one configured the same way the old one was.  Or update the image tag to the release you want in your docker-compose file (if you are using that), then bring down the orchestration and start it back up again.

When the API starts up, it checks the state of the database to determine if any changes are needed for the new version, and then makes them. These changes can occasionally take more than a few minutes to run if your data set is large.
We note these "Database Migrations" in our Release Notes, in case deployments want to take an extra snapshot or something before running it in addition to their normal backups. 

Most updates do not require database migrations.

Hope that helps, I'll close this issue when I add this info to the Docs!

**Comment by AkashiyaWolf** [comment]
That does help, but leads me with a follow up question. My STIG Manager server is on a disconnected network. How can I pull down the new container images without having to do a docker-pull?

**Comment by cd-rite** [comment]
@AkashiyaWolf  You'd have to do the docker pull from a connected machine, then transfer the image to the disconnected machine, then do a `docker load` of the new image to make it available.  That should be the same as however the original image made it onto the disconnected machine in the first place....The docker docs should be able to help with this process!

**Comment by AkashiyaWolf** [comment]
That's what I thought the answer was. Thanks for confirming!
