### ISSUE TITLE
Unable to import certain STIG Benchmarks with large number of assets 

### ISSUE THREAD

**Issue by vogtjob** [NUWCDIVNPT/stig-manager#1296]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of STIG Manager?

- [X] I am using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases).
- [ ] I am NOT using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases). I am aware that the first thing I will be asked to do is update the application so that I have the latest bugfixes.

### Where are you experiencing the issue?

- [X] API
- [ ] UI or other client
- [ ] Deployment
- [ ] Elsewhere

### Current Behavior

When uploading benchmarks on an instance with a large number of assets with that benchmark the import fails.  Initial errors indicate a lock_wait_timeout within mysql.  I increased the innodb_lock_wait_timeout to 1000 (from the default 50) to see if this remedied the error to no avail.  Other mysql parameters set are sort_buffer_size=128M, max_connections=1000, innodb_buffer_pool_size=1024M.

After increasing the innodb_lock_wait_timeout I'm not getting the lock_wait_timeout, but the application is unusable (probably due to locks on the DB).

We do not experience this issue on our smaller instances and the same benchmarks import correctly.

Just for reference one of the failing benchmarks is U_MS_Windows_10_V2R9_Manual_STIG

### Describe your Environment

```markdown
- Hosting: Podman containers
- Browser: Edgs, Chrome
- OS:RHEL 8.9
- Node:
- npm:
```

**Comment by vogtjob** [comment]
Update.  With the settings mentioned above, the benchmark did load, but the process took about 90 minutes to complete.

**Comment by cd-rite** [comment]
Hi @vogtjob Wow, thank you for the report, and I'm glad you were able to get by that immediate issue.  

We are going to rollback the latest metrics enhancement (Adding resultEngine and user aggregations) since they are having significant performance impact on large deployments.  **We should have a 1.4.11 within a day or so that should restore previous performance.**  Increasing MySQL resources, as you have done, is our recommendation for 1.4.10 right now (and/or hold off on importing new reference STIGs until 1.4.11).  

We will be working on enhancing our testing scenarios to better simulate large deployments and will revisit this feature in the future. Thanks again for the report and patience with this issue!

**Comment by cd-rite** [comment]
Hi @vogtjob This issue should be resolved with the rollback of the new metrics fields in Release 1.4.11
