### ISSUE TITLE
BUG: Can't Import Multiple SQL Database STIG CKls

### ISSUE THREAD

**Issue by sagansapien** [NUWCDIVNPT/stig-manager#256]
For a single SQL 2016 database server, I have quantity 5 SQL Server 2016 Database checklists (because this server has 5 different databases under it's SQL instance). This is the same STIG checklist is repeated 5 times, each documenting checks/results for different databases on the same system.

I think stigman is posting the same STIG data over the same single checklist, so whichever CKL finishes processing last is what you end up with.

Somehow, I need to track 5 different CKLs for the same STIG within the same asset.

Thanks

**Comment by cd-rite** [comment]
STIGMan's approach to this is that an "Asset" is equivalent to the "Target" of Evaluation, which does not have to be a computer (hence the non-computing flag available to Assets)! In this case, that target is the specific database that is being evaluated, not the host it resides on at that moment (especially since DBs in many environments can migrate).

Our suggestion would be to Create an Asset for the host, and one for each DB being evaluated.

**Comment by csmig** [comment]
I've worked out a solution that can be implemented on the client sides (watcher and the web app) and won't require a change to the backend data model. But it does require that ES sets the WEB_DB_INSTACE tags uniquely.

STIG Manager API would maintain a distinct Asset for each CKL hostname/database pair (or hostname/site pair). The import tooling will map an incoming ES CKL to the Asset by referencing certain Asset metadata properties (probably cklHostname, cklWebDbInstance and cklWebDbSite). If the tooling needs to create the Asset, it will set this metadata and set the initial Asset name to a concatenation of HOST_NAME and WEB_DB_INSTANCE,. However, the name is not meaningful in this solution and it can be changed later. Folks can also create an Asset manually if desired and manually set the metadata.

The metadata properties will be referenced when the web client exports a CKL, so the desired HOST_NAME, WEB_DB_SITE, and WEB_DB_INSTANCE will appear in the CKL regardless of the SM Asset's name.

**Comment by sagansapien** [comment]
https://spork.navsea.navy.mil/nswc-crane-division/evaluate-stig/-/issues/174

**Comment by sagansapien** [comment]
Can this be expanded to account for database instances? So, hostname/instance/database pairs instead of just hostname/database? This should account for common default databases which are named the same across multiple instances on the same host.

**Comment by cd-rite** [comment]
Yeahhhh it's a tricky problem because the ckl tags available are not that straightforward, and seem designed for a time when it was always possible to tie a target of evaluation back to a specific physical host. 

Our new implementation uses the <WEB_OR_DB> tag set to true to invoke this special processing that will account for these other tags and produce unique assets for them (and generate equivalent ckls). 

It will store info from these tags as Asset metadata and create its own host name from a combination of these existing ckl tags and the host name:
<WEB_OR_DB_SITE> 
<WEB_OR_DB_INSTANCE> 

I think from our point of view it doesn’t matter too much what you put in those fields (though that backslash might be a problem?) as long as they can sum to a unique combination of hostname-site-instance. 
You could use the <WEB_OR_DB_SITE> for the cluster and <WEB_OR_DB_INSTANCE> for the instance, perhaps?

**Comment by direland69** [comment]
Ok, we can do that.  So just for clarity on a SQL Instance CKL...

`Host Name` = Physical Server name
`WEB OR DB SITE` = Physical Server name OR Cluster name depending on config
`WEB OR DB INSTANCE` = SQL Instance name

But what about for a SQL Database CKL?  As stated previously, if a SQL server has multiple instances (e.g. SQL01, SQL02) then each of those instances will have the common databases - master, temp, etc.  Where and how do we want to record the database name?  I would think under `[WEB_OR_DB_INSTANCE]` as `[InstanceName]\[DatabaseName]`.  We can use whatever separator is most friendly for STIG Man.

**Comment by cd-rite** [comment]
That should work! 
Since we are just storing these fields as metadata attached to an asset, we can recreate the .ckl with whatever you put in those fields.
We will create an internal asset name out of all those components, which we expect to be unique, and it sounds like what you are thinking of doing will work for that. 

We do use the STIGMan asset name (which the user can change if they want, without affecting functionality), as the base for the filename produced by our .ckl exporter.  Since those fields could be part of our Asset name, I'd suggest only using characters that will work in filenames as the separator. It's not really a big deal, as we will wind up substituting alternate characters if they are invalid anyway, but just in case you want them to match!

**Comment by csmig** [comment]
@direland69 Fantastic tool you've created, thanks for joining the discussion. A correction on the element names under discussion, they are `<WEB_DB_SITE>` and `<WEB_DB_INSTANCE>`. No `OR` in there.

My two cents:
As @cd-rite noted, we are unopinionated about the semantics of `<WEB_DB_SITE>` and `<WEB_DB_INSTANCE>`. They are sadly all that CKL offers to represent parent-child relationships and the semantics are ambiguous.

For example, the current STIG Library provides these STIGs:

| Technology | Has Parent/Child | Parent | Child |
|:--|:-:|---|---|
|***Database***|
|Oracle Database 11g|Yes|Installation|Instance|
|Oracle Database 11.2g and 12c|No|--|--|
|SQL Server 2014 and 2016|Yes|Instance|Database|
|Oracle MySQL 8|No|--|--|
|PostgreSQL 9|No|--|--|
|***Web***|
|Apache 2.2 and 2.4|Yes|Server|Site|
|IIS 8.5 and 10|Yes|Server|Site|
|Oracle HTTP Server|No|--|--|

This is a terminology mess that is frustratingly common in the STIG domain. If I were to be opinionated, I would probably represent the parent as `<WEB_DB_INSTANCE>` and the child as `<WEB_DB_SITE>`. Siblings could be readily identified because they share the same `<WEB_DB_INSTANCE>`.

Finally, I would avoid names with slashes but to each their own. I think the safest practice to follow is the [Google JSON Style Guide](https://google.github.io/styleguide/jsoncstyleguide.xml) for [property names](https://google.github.io/styleguide/jsoncstyleguide.xml#Property_Name_Format):

- Property names must be camel-cased, ascii strings.
- The first character must be a letter, an underscore (_) or a dollar sign ($).
- Subsequent characters can be a letter, a digit, an underscore, or a dollar sign.

**Comment by direland69** [comment]
Underscores as a separator could be confusing because many databases use underscores in their name.  But, what if we enclosed the Instance and Database name in quotes and then separated with an underscore?:

`"SQL01"_"CM_SCR"`

**Comment by cd-rite** [comment]
@direland69 It will not matter to our tool what is used, since it will treat these fields as strings internally. 

However any Asset name we construct out of those fields will be used as part of a filename if the user exports. **This will still work fine,** as will perform substitutions on that filename so that all characters are valid filename characters anyway, it was just something I wanted to point out in case you wanted them to match. Whatever internal representation you pick will be carried through **inside** .ckls we produce without alteration since we are storing it in freeform metadata fields.  The only issue is filenames on export, which will be restricted based on OS. For example, [Windows](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file):

> Use any character in the current code page for a name, including Unicode characters and characters in the extended character set (128–255), except for the following:
The following reserved characters:
\< (less than)
\> (greater than)
: (colon)
" (double quote)
/ (forward slash)
\ (backslash)
| (vertical bar or pipe)
? (question mark)
\* (asterisk)


Wherever we need to create a file, if it has one of those characters, we will likely replace it with a dash ('-').

**Comment by sagansapien** [comment]
I tested generating new SQL 2016 database/instance CKLs with the development version of Evaluate-STIG which addresses this. Import looks good.

**Comment by Vertical-alignment41** [comment]
> Can this be expanded to account for database instances? So, hostname/instance/database pairs instead of just hostname/database? This should account for common default databases which are named the same across multiple instances on the same host.





https://stackdev.space/questions/exploring-the-depths-of-xml-parsing-for-sql-server-with-numerous-nested-child-elements
