### ISSUE TITLE
FEATURE REQUEST:  Asset description needs added as a viewable column option

### ISSUE THREAD

**Issue by dtester1** [NUWCDIVNPT/stig-manager#554]
Issue:  Asset Description can be set in a collection under manage and then choosing properties but isn't viewable as column option.  
Request:  Add Asset Description as a viewable column option in manage, collection review and reports. 
Rationale:  Without Asset Description showing up as a column option its hard to know what the asset is by just its asset name (ex. what type/purpose is a server or device).

**Comment by cd-rite** [comment]
That's for submitting an issue, @dtester1 !
Descriptions can be fairly lengthy (though they are capped at 255 characters, presently), which would take up most of a row.  

When we address this we will likely add it as an optional column in the places you suggest, which may then be displayed truncated if necessary (indicated by an ellipsis ) and then display any overflow Description text in in a pop-up tooltip for that row. 
We will let you know when we implement!

**Comment by dtester1** [comment]
I recently discussed this item some with team members.  We don't really need something as big as the description field being displayed.  I am not sure if it might also be possible or better to consider adding a shortened asset tag (or whatever term is appropriate) instead of the 255 character description and have that displayed in columns.  Examples:  Workstation, Admin Workstation, SQL Server.  A few words to identify item on the column views and reports is really what we are looking for as hostnames aren't descriptive to know what the device is.

**Comment by cd-rite** [comment]
Hi @dtester1 
Thanks for the feedback on this, and #561 !
I had wondered if there was some overlap in your use case for this feature and for the one in the other proposal.  I appreciate the user's feedback and your attempt to make use of the feature set we have implemented so far. However, these user stories might be best addressed by a new feature. 

I think our proposed solution there, tagging, could accomplish what you are trying to do here.  Our goal is to make it more directly relevant to organizing than the "description" field and more approachable for users than a whole metadata implementation. 

Since it sounds like you are interested in seeing how tagging turns out too, I'll close this issue to help prioritize the tagging feature. 
You can always reopen this issue later if you want! 

Initial work on the tagging feature is being tracked in issue #566
