### ISSUE TITLE
BUG: CKL Import stuck

### ISSUE THREAD

**Issue by sagansapien** [NUWCDIVNPT/stig-manager#58]
Collection > Assets > _hostname_ > _STIG name_ > "Checklist" drop down >  Import Results...

This CKL import still shows the verbose output, which is probably fine from a performance perspective because you're only importing a single file here anyways.

However, the "Importing file" dialogue appears to be stuck on "Initializing". The results appear to be importing, but it never says "Finished > Done" and remains "Initializing".

Thanks

**Comment by csmig** [comment]
Yes, this part of the UI needs work. There are additional issues with it, which I'll write up below soon. For now, I think you'll find the import *did* happen, only the feedback is lacking. Please advise us if you can demonstrate otherwise!

**Comment by csmig** [comment]
I've addressed the basic issue with the UI appearing to be stuck, by adding a completion message to the progress bar.
However, we should open a feature request for this part of the UI to provide more robust vetting and previewing of the CKL or SCAP file.

When the issue is created, I'll link to it here.
