### ISSUE TITLE
BUG: Vulnerability Status Being Changed to Informational

### ISSUE THREAD

**Issue by tylerforajter** [NUWCDIVNPT/stig-manager#584]
**Bug Location**

I found a bug in the:
- [ ] API
- [ X] UI
- [ ] Elsewhere (Please specify):

**Bug Description:**
Upon manually uploading an updated copy of a STIG, I noticed that the status on some findings was changed to "Informational".  Please see below image:

![image](https://user-images.githubusercontent.com/100237457/155223423-c92a677f-9877-48e7-8f5f-20aa7f25db5c.png)

I then checked the raw CKL file to see what was uploaded.  See Image below:

![image](https://user-images.githubusercontent.com/100237457/155223540-d47ec393-79e5-4fe4-a25f-2473244cd148.png)

As you can see, the file that I uploaded had a status of "NR" for the check in question.  However, upon import into STIGMAN, the status was changed to informational.  

On the same note, I noticed that this did not occur for a different check.  In STIG viewer, the following check was listed as "NR"
![image](https://user-images.githubusercontent.com/100237457/155224027-0fe087ee-45ea-4ab6-b4e0-e397e3d7f1d7.png)

However, in stigman, the status was not changed to "informational"
![image](https://user-images.githubusercontent.com/100237457/155224239-8063a35a-0bbf-40a3-ab66-6c7a253e55ae.png)

And the history did not show anything new.
![image](https://user-images.githubusercontent.com/100237457/155224346-8e6760e1-2601-48dc-83d4-3c936383ec49.png)

I'm not sure if this is a bug, or if I'm just unaware of the backend logic.  Why does it change to informational for only some imports?  Is there a way to not mark anything informational?

- [X ] I have checked to see if there is already an existing issue that describes this bug.

**To Reproduce**
1. Upload a stig
2. reupload a stig with different data
3. Verify that the check has been marked informational. 

**Expected behavior**
I would expect stigman to reflect whatever is uploaded via the ckl.
**Actual behavior**
The check was marked informational.

**Screenshots**
![image](https://user-images.githubusercontent.com/100237457/155225028-8d5ac04b-d207-41c2-bcfb-ab06f97bf5e1.png)
![image](https://user-images.githubusercontent.com/100237457/155225098-3117ce81-b036-47be-9a11-de353e004b88.png)

**Environment or Configuration:**
 - Container or Orchestration info
 - Browser
 - Other info

**Additional context**
Happy to provide any additional details as necessary.

**Comment by cd-rite** [comment]
Hi @tylerforajter 
That is expected behavior, documented in a note here:
[https://stig-manager.readthedocs.io/en/latest/user-guide/user-guide.html?highlight=informational#a-note-on-ckl-processing](https://stig-manager.readthedocs.io/en/latest/user-guide/user-guide.html?highlight=informational#a-note-on-ckl-processing
)
 "STIG Manager does not typically import .ckl reviews with a “Not_Reviewed” status. However, if a “Not_Reviewed” result includes data in the “Finding_Details” element, it will be imported with a result of “Informational”. Upon export as a .ckl, any Informational results that remain will be generated with a “Not_Reviewed” status once more."

That note should be updated to mention that content in either the Finding Details or Comments fields will trigger this behavior.
The intent for this behavior was to have a way to distinguish that a Rule was "Not Reviewed" but did include some information in the comment field(s), vs those Rules that were Not Reviewed at all.

We have found this indicator be be helpful when using the UI, but not all tools use these extended Status options, so .ckl exports will collapse Informationals back to Not_Reviewed.

So, I would say this is not a bug, but we may have the beginnings of a Feature Request!  If you, for example, would like to make this behavior optional on import, please create a Feature Request Issue! 

Feel free to re-open this issue if there is some aspect of this issue I have not covered, but otherwise I will close this issue. 

Thanks for using STIGMan!

**Comment by tylerforajter** [comment]
Thanks for providing that link to the docs!  Much appreciated!!!
