### ISSUE TITLE
FEATURE REQUEST: Disable Informational Status

### ISSUE THREAD

**Issue by tylerforajter** [NUWCDIVNPT/stig-manager#585]
**Is your feature request related to a problem? Please describe.**
Please see Issue #584 for reference.

**Describe the solution you'd like**
I would like to be able to disable the "Informational" status when importing a stig via the UI or stigman watcher.  We have automation that automatically evaluates the stig, and we would like stigman to reflect exactly what the evaluation tool has found.    

**Additional context**
Please see Issue #584 for reference.

**Comment by cd-rite** [comment]
Thanks, @tylerforajter fore creating the feature request.
We will consider this request, but "Not Reviewed" rules are represented by the absence of *any* Review data in the STIGMan architecture. When tools like Evaluate STIG reviews a Rule for an asset and provides commentary, but does not make an assessment status decision, that Rule was still "Reviewed," it just does not yet have a status assessment. In order to accept the commentary, we need to attach a Status to it.   Implementing your feature would require re-examining our treatment of Reviews of this type. 

Our goal at the moment is not necessarily to represent .ckl inputs exactly, but to accurately represent the overall status of a Review. .ckls are broadly used, but that format does not have a published schema and sometimes unannounced changes are made to it. The XCCDF format, which DOES have a published format, includes Informational as a valid Status. We ensure our imported and exported .ckl files are compatible with the DISA STIG Viewer tool, but want our internal representation to be flexible enough to support these overlapping standards. 

There is some more discussion on this topic, which led to the current behavior, here:
https://github.com/NUWCDIVNPT/stig-manager/issues/67

**Comment by dtester1** [comment]
In our view an item isn't reviewed if it doesn't have a status.  Review to us is the admins are done reviewing the check.  Here is where the issue comes in:  We were looking use the STIG View under manage to report review of STIGs completed. Marking the items I is marking that the checklist has been reviewed and causing a miscount.  Can it be done so that I does not count as reviewed instead is still not reviewed in this type of view?

**Comment by csmig** [comment]
Yes, that is reasonable behavior that I think should be implemented.

**Comment by dtester1** [comment]
Yes that sounds correct.

**Comment by dtester1** [comment]
Do I need to put a new feature request in for review count to exclude those items?  Also how hard is this change going to be?
I ask because this is immediately affecting us and our site rollout as we were planning to use those review counts instead of previous metrics at regular weekly meetings so management knew which STIGS needed to have focus on from administrators to complete.

**Comment by cd-rite** [comment]
Hi @dtester1 
Yes, please submit a feature request to alter that behavior. The change should not be too difficult, but we will need to assess. 

Are you using the the "Submitted" status at all in your process? If you are, that column in the Status Report (and Collection Manager screen) should reflect the count you are looking for, as "Informational" reviews cannot be submitted, only those that have one of the traditional Results can be set to "Submitted" status.

**Comment by csmig** [comment]
Closed by #659
