### ISSUE TITLE
FEATURE REQUEST: Allow users to set default configurations

### ISSUE THREAD

**Issue by mayszs** [NUWCDIVNPT/stig-manager#609]
**Is your feature request related to a problem? Please describe.**
By default STIGMAN shows all checks by Rule ID with a one time option to view by Vulnerability ID.
Many organizations manage POA&Ms and tracking by vulnerability ID.

**Describe the solution you'd like**
Allow a user to select rule ID or Vulnerability ID and have it default to the preferred setting.

**Comment by cd-rite** [comment]
Hi @mayszs Thanks for the suggestion! We have internally discussed the need for some persistent user preferences, and I'll add this to the list when we address it. 

We have considered making Group/Vulnerability ID the default view, but the issue there is the Rule Titles are MUCH more descriptive and helpful.  The Group Titles are often things like "WN10-00-000050" whereas the Rule Title will be "Local volumes must be formatted using NTFS."  We have found that to be useful when manually reviewing checklists.

The Findings report does default to aggregating on Group because that is the report that is "closest" to the POA&M part of the process.

**Comment by cd-rite** [comment]
Compromise!  STIG Manager now defaults to display Group ID and Rule Title in most views. The best of both worlds. 
Resolved with PR #640
