### ISSUE TITLE
FEATURE REQUEST: Include STIG Version and Release in CKL filename

### ISSUE THREAD

**Issue by mayszs** [NUWCDIVNPT/stig-manager#610]
**Is your feature request related to a problem? Please describe.**
When exporting the most recent set of STIGs from STIGMAN they are labeled as Latest instead of including the actual Version and Revision Number. STIGMAN does include this information if exporting previous releases of STIGs.
Having the CLKs labeled as latest while working on a package submission where you need to validate the STIG release against the SAP testing requirements. Additionally "latest" becomes meaningless the moment a new revision is released.
From a consistency and package management perspective the version and release data being in the CKL title is necessary.
**Describe alternatives you've considered**
To correct the filenames after being exported would require renaming all of them manually or by script every time a set of testing data needs to be uploaded to eMASS.

**Comment by cd-rite** [comment]
Hi @mayszs Thanks for the suggestion! I agree, the specific revision vs "latest" in the filename would be more useful. 
I do have a workaround that might work for you for now:
From the Collection Review workspace, if you manually choose the latest revision from the Checklist pulldown menu, the .zip archive produced will have filenames that include the specific revision, rather than "latest."
![image](https://user-images.githubusercontent.com/61710958/157912314-f3a69aef-1b2c-4b3e-8797-41df85917f84.png)



(Note to team - this only applies to the .zip archives downloaded from the Collection Manage and Collection Review workspaces.  The individual Asset/STIG downloads always have the revision in the filename)

**Comment by jeremygifford** [comment]
I second adding the option to have the versions included in the exports at the collection level (so if you have 70 STIGs you don't have to do an export for each).

I'd also like to add in the guidance from the Navy RMF Process Guide section A.1 which specifies filenames that we upload to eMASS should be of the format: "SYSTEMACRONYM_DOCNAME_DATE.DOCTYPE". Something like "<collection name>_<hostname>_<STIG Title + version / revision>_<date last modified>.ckl"

A good future addition for handling the assorted naming conventions various organizations may have would be a means to customize it via the UI. Something like combining one or more drop-downs with a list of potentially relevant fields from the database.
