### ISSUE TITLE
Add `resultEngine` property to Review 

### ISSUE THREAD

**Issue by cd-rite** [NUWCDIVNPT/stig-manager#629]
Review and Review_history objects should have properties that record automation engine information (ie. SCAP, Eval STIG). 

Tentative object definition (using NISTIR 7275r4 for overrides): 
```
engine: { 
  name: string
  version: string
  type: enum of 'scap', 'script'
  resultTime: iso8601 datetime
  overrides:[ 
    {
     oldResult: string
     newResult: string
     remark: string
     time: iso8601 datetime
     authority: string
    }
]
```

**Comment by csmig** [comment]
Comments welcome...

Currently, the API contains no business rules that reference `autoResult`. I propose we deprecate `autoResult` for this new `engine` property and schedule the removal of `autoResult` from the API and database. `autoResult` will no longer be required when creating a Review, and the `engine` property will also be optional.

Our clients (web, Watcher) currently set `autoResult: true` only when importing XCCDF TestResults. We have presumed all XCCDF was generated by the SCC tool (note the comment we inject, "SCC reviewed..."). We should stop assuming that! Nonetheless, because of our current practice, I think we should migrate all existing Review and ReviewHistory records with `autoResult: true` to also have `engine: { name: 'scc' , type: 'scap'}`. 

During the deprecation period, any POST/PATCH request that sets `autoResult: true` (and does not also contain an `engine` property) will be stored by the API with property `engine: { name: 'scc', type: 'scap }`.

**Comment by csmig** [comment]
Proposed OAS schema for `engine` property of Review
```
ReviewEngine:
  type: object
  additionalProperties: false
  properties:
    name:
      $ref: '#/components/schemas/String255'
    version:
      $ref: '#/components/schemas/String255'
    type:
      $ref: '#/components/schemas/ReviewEngineType'
    resultTime:
      $ref: '#/components/schemas/StringDateTime'
    overrides:
      type: array
      minItems: 0
      items:
        $ref: '#/components/schemas/ReviewEngineOverride'
  required:
    - name
    - type
ReviewEngineOverride:
  type: object
  additionalProperties: false
  properties:
    authority:
      $ref: '#/components/schemas/String255'
    oldResult:
      $ref: '#/components/schemas/ReviewResult'
    newResult:
      $ref: '#/components/schemas/ReviewResult'
    remark:
      $ref: '#/components/schemas/String255'
    time:
      $ref: '#/components/schemas/StringDateTime'
  required:
    - authority
    - oldResult
    - newResult
ReviewEngineType:
  type: string
  enum:
    - scap
    - script
    - other
 ```
