### ISSUE TITLE
BUG:  When using the API to get an asset, the noncomputing attribute is not valid

### ISSUE THREAD

**Issue by dante2365** [NUWCDIVNPT/stig-manager#680]
**Bug Location**

I found a bug in the:
- [x ] API
- [ ] UI
- [ ] Elsewhere (Please specify)

**Bug Description:**

- The bug is in the get asset api endpoint
- Including your actual request may be helpful as well.

- [ ] I have checked to see if there is already an existing issue that describes this bug.

**To Reproduce**

**Expected behavior**
The getasset should return the noncomputing attribute as "false" instead of "False".  When we call the patch asset endpoint, with the results of getasset, it is sending back an error saying the noncomputing field must be a boolean.  We worked around this problem by lower casing the noncomputing attribute after get asset then calling patch asset. 

**Actual behavior**
What behavior did you actually experience?

**Screenshots**

**Environment or Configuration:**
 - Docker
 - Browser
 - Other info

**Additional context**
The results of the getasset should be a valid payload for the patchasset endpoint.

**Comment by cd-rite** [comment]
Hi @dante2365 
The GET /assets/{assetId} endpoint is properly returning a boolean value for the noncomputing attribute (no quotes around false). 

Perhaps some component in your client is serializing the value as that upper-cased string?

**Comment by dante2365** [comment]
We are able to work around this but I wanted to point out that it is coming back as **F**alse instead of **f**alse from the get asset endpoint.  When taking this payload and calling patch with **F**alse we are getting an error from the stig manager api saying noncompute must be a boolean.  Here is the raw result we get back from the get asset api call (could be a .Net peculiarity with their httpClient object as we are using .Net Core 3.x to call the get asset endpoint).  Just an FYI.. 
![image](https://user-images.githubusercontent.com/53409387/173662790-43fa2b57-5c7d-4b61-b07d-87cf94560cb3.png)

**Comment by cd-rite** [comment]
Hi @dante2365 
I think you're seeing an artifact from .Net... In your screenshot, you can see False is not in quotes, so it's not a string. .Net or perhaps VS22 viewer is capitalizing it's **representation** of the boolean we return in our JSON response, and somehow you are using that representation in subsequent processing, rather than the actual JSON object we return (Content-Type: application/json;).  

If you check with curl, or even chrome dev tools while using the app, you'll see that responses to GET assets do return a proper, lower-cased JSON boolean value.
