### ISSUE TITLE
BUG: Completed checklists appear as NR in STIG-Manager

### ISSUE THREAD

**Issue by pandasquare23** [NUWCDIVNPT/stig-manager#705]
**Bug Location**

I found a bug in the:
- [ ] API
- [x] UI
- [ ] Elsewhere (Please specify)

**Bug Description:**

- If bug is in the API, please specify endpoint.
- Including your actual request may be helpful as well.

- [x] I have checked to see if there is already an existing issue that describes this bug.

**To Reproduce**

Unsure how to have you replicate this bug.

From my end I import completed ckls (verified) into a specific collection. Parsing completes as expected with no errors. The results for each asset are listed correctly in the import pop-up (in this case it's 0 NR, 3 NA, 48 NF, and 0 Open). I make sure the "Import Reviews" box is selected and click "Add to Collection"

Importing data finishes as expect and POSTs the reviews for each assetId.

When I go to review the data for the particular STIG ckl it shows them as completely empty.

**Expected behavior**
The ckl data should be imported successfully and available for review in STIG-Manager

**Actual behavior**
No ckl data is imported. All STIG items appear as NR.

[**Screenshots**](
![Capture_1](https://user-images.githubusercontent.com/72846806/178331300-1a4f3e88-0e24-4d7c-b603-090c7565cb01.PNG)
![Capture_2](https://user-images.githubusercontent.com/72846806/178331305-ddcd5376-6af5-43c6-99c0-f5fbba8c0997.PNG)
![Capture](https://user-images.githubusercontent.com/72846806/178331287-2c92b60a-8ed7-4664-a7e0-1099e39afc05.PNG))
Screenshots added that show the import parse results (capture). The successful POST (capture_1) and the resulting STIG collection with no data (capture_2). Asset names have been removed as a precaution.

**Environment or Configuration:**
 - Container or Orchestration info
 - Browser
 - Other info

**Additional context**

**Comment by cd-rite** [comment]
Hi @pandasquare23 -
I think you are running an older version of STIG Manager. The latest version is 1.2.10, and recent versions provide more helpful feedback when importing results, which would be useful here.

Aside from that, I suspect you may have imported a .ckl for an earlier release of that STIG. In most cases, this doesn't matter too much as the STIGs are substantially the same. However, sometimes the DISA release will have changed ALL Rule IDs, so STIGMan will import the file, but there will not be results associated with the RuleIds for the *latest* version of the STIG.
It looks like they did this for Cisco_IOS_XE_Switch_NDM_STIG between Version 2 Release 1 and Version 2 Release 2.

From your screenshot, you have V2R2 installed in STIG Manager.  If you open up the .ckl file in a text editor, you should be able to verify the Version and Release.  Version is usually located around line 23 (your line numbers may vary, though):
```
<SID_NAME>version</SID_NAME>
<SID_DATA>2</SID_DATA>
```
and Release is around line 45:
```
<SID_NAME>releaseinfo</SID_NAME>
<SID_DATA>Release: 2 Benchmark Date: 27 Oct 2021</SID_DATA>
```
I think you may have Release: 1 rather than Release: 2.

You can also get some more info about your import from the "Importing Results" screen that is available in the latest version of the app. 
I'd recommend you update, verify the STIG version in the .ckl, and then try again.

**Comment by cd-rite** [comment]
HI @pandasquare23 
Alas, DISA does not note RuleId changes in their Release Notes, and if you compare the RuleIds, you will see they all changed. 
If you don't have V2R2 .ckls, you can install the V2R1 STIG into STIGMan using the Application Management interface. Then, select it using the Checklist Pulldown Menu from the individual Asset Review Workspace. You will see all your imported Reviews there immediately.

You can also delete V2R2 (once you've installed V2R1!) using the Application Management interface, which will cause V2R1 to become the default version for display and calculating statistics. 

DISA doesn't seem to make older versions available, but I happen to have it:
[U_Cisco_IOS_XE_Switch_Y21M04_STIG.zip](https://github.com/NUWCDIVNPT/stig-manager/files/9094659/U_Cisco_IOS_XE_Switch_Y21M04_STIG.zip)
