### ISSUE TITLE
FEATURE REQUEST: Assessment (filter/view/workspace) based on SAP

### ISSUE THREAD

**Issue by jeremygifford** [NUWCDIVNPT/stig-manager#712]
**Is your feature request related to a problem? Please describe.**

There does not appear to be a way to make changes to the Asset to STIG map without destroying history when associations are removed. Besides maintaining a history, not every assessment (targeted assessments like use-cases when updates have been made to an enclave) will be looking at every asset and STIG.

**Describe the solution you'd like**
"assessment iteration views" or filters based on Asset to STIG maps separate from the overall repository. For example when starting a new re-authorization or use-case, upload a .csv map of STIGs to assets that will be assessed (per the SAP). Once uploaded provide an option to filter or provide a view (perhaps could be described as a workspace maybe?) based on that map to see which asset/STIGs are already complete and which don't yet exist in the overall collection. Finally, be able to do a CKL export matching that map, ignoring everything else in the collection.
[example_STIG_to_Asset_Map.csv](https://github.com/NUWCDIVNPT/stig-manager/files/9134397/example_STIG_to_Asset_Map.csv)

**Comment by cd-rite** [comment]
HI @jeremygifford I think some of this is more in eMasster's wheelhouse, as I think it can already handle SAP  and .ckl inputs.
Our unaggregated metrics exports now also export lists of Assets and their STIGs, which could be compared against the SAP in Excel.  We are also working on a Collection copy feature that may be an easier way to create a "working" or "process" copy a Collection, while leaving the "live" Collection alone so that it can be used to respond to actual security states.   

Closing for now since this tool and others have evolved since last year. Thanks for the input, feel free to reopen/discuss some more, though.
