### ISSUE TITLE
Possible Bug: Metrics Mismatch

### ISSUE THREAD

**Issue by jeremygifford** [NUWCDIVNPT/stig-manager#733]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of STIG Manager?

- [ ] I am using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases).
- [X] I am NOT using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases). I am aware that the first thing I will be asked to do is update the application so that I have the latest bugfixes.

### Where are you experiencing the issue?

- [ ] API
- [X] UI or other client
- [ ] Deployment
- [ ] Elsewhere

### Current Behavior

Version 1.2.12

Collection > Management > Asset and STIG tables show 100% completion, Reports > Status shows 0 not checked - specific STIG results under the asset show 2 NR without any comments and CKL export is also NR with blank comment fields.

### Expected Behavior

2 NR reflected in all metrics.

### Can you provide screenshots, logs, or other useful artifacts?

![StatusMismatch_1](https://user-images.githubusercontent.com/78163427/183137068-55712960-49d8-4605-a5c5-bd265f227b13.JPG)
![StatusMismatch_2](https://user-images.githubusercontent.com/78163427/183137076-d9014366-2125-4f7d-8b79-8185cb4f7ea0.JPG)
![StatusMismatch_3](https://user-images.githubusercontent.com/78163427/183137085-f4dd982b-e7e3-49df-9bab-26dbdcd4480c.JPG)

### Describe your Environment

```markdown
- Hosting: NREN STIGMan version 1.2.12
- Browser: Edge
- OS: Windows 10
- Node:
- npm:
```

**Comment by cd-rite** [comment]
Hi @jeremygifford Thanks for the report.....
The issue you are describing seems to be related to that particular STIG..... The latest DISA release includes a bundle of VMWare STIGs that include the PostgreSQL one you are having an issue with.
It looks like they released an OLDER version of the STIG (status date="2021-03-18") than the one from the previous library (status date="2021-04-15") with the SAME Release, Version, and Release date fields!!!

There are 2 new/old Rules in the one they just released (You can see in the older STIG files how those group numbers were skipped), so there are 20 Rules in the "old" one (with the later status date), but 22 in the "new" STIG (with the earlier status date), even though they have the same Release/Version numbers....!!!  This is of course throwing off our status calculations, since they have two STIGs with the same release info.

I'll let you know when/if/how we come up with a solution to address this.  

In the meantime, you could report this discrepancy to DISA: disa.stig_spt@mail.mil
I will send them an email too.
Thanks!

**Comment by jeremygifford** [comment]
That's hilarious, as if it wasn't bad enough with DISA frequently changing STIG_IDs, now we can't even trust version/release numbers!

**Comment by cd-rite** [comment]
Hi @jeremygifford and @TheTroubleshooter
It's not the most elegant workaround, but I wanted to provide you with a procedure that would preserve your current STIG assignments, and not cause an issue when DISA inevitably releases ANOTHER version of this STIG with the proper Release/Version info.

1. Decide which version of V1R1 for the VMWare PostgreSQL STIG you want to use ( status date="2021-04-15" or "2021-03-18")
2. Open the reference XCCDF file for that particular version of the STIG that you downloaded from DISA. 
3. Look for the `<version>1</version>` element, and change it to `<version>0</version>`
4. Import that modified file into STIGMan from the App Management interface. 
5. Delete the V1R1 version of the STIG using the same interface. 
6. This will leave you with the "current" STIG in STIG Manager (whichever you decide that should be), as Version 0 Release 1, leaving room for a re-release of Version 1 Release 1 that will not clobber the "current" version in STIG Manager. 

**Optional:**
7. Re-import the unchanged version of the STIG that you want to keep as Version 1, Release 1. This will ensure when you export, it will have the revision you expect, **however** DISA might re-release V1R1 **again** with different content. If that happens, you will have to DELETE V1R1 before importing or, or perform this procedure again and in this step import the latest one they release, instead of the same one.  If they release a Version 1 Release **2** this will not be an issue. 


If you want both versions, just change the Version to 0 in both files, and change the Release text in the element `<plain-text id="release-info">Release: 1 Benchmark Date: 09 Mar 2021</plain-text>` to 0 for the "old" one, and leave as 1 for the one you want as the default. They will show up as V0R0 and V0R1 in STIGMan.

**Comment by cd-rite** [comment]
Closing this issue and assuming the work-around is sufficient. For STIGs with identical release information, users will have to choose which one they want to use in the system, or manually change their reference STIG to keep them separate.
