### ISSUE TITLE
FEATURE REQUEST: Add STIG ID to Available Display Options

### ISSUE THREAD

**Issue by dtester1** [NUWCDIVNPT/stig-manager#816]
**Is your feature request related to a problem? Please describe.**
Add STIG ID not present in STIG Manager so DISA STIG Revision History can be compared to STIG data in STIG Manager 

**Describe the solution you'd like**
Add STIG ID just like Rule ID and Group ID under displayed title option just like Rule ID and Group ID

**Describe alternatives you've considered**
No other options that can think of where this information makes sense.

**Comment by dtester1** [comment]
how difficult is this going to be?  I got this asked by local IA folks and system admins as they use revision history for their work and have lost that functionality in STIG Manager vs STIG Viewer.  They end up using STIG Viewer still I was told.

**Comment by csmig** [comment]
Thanks for the reference to the Revision History docs from DISA, it is the first context I've seen where the STIG ID value is used.

Fortunately, STIG Manager was already storing this value, known as `<rule version>` in XCCDF and `Rule_Ver` in CKL. I've opened a PR that adds an initially hidden **STIG Id** column to the workspaces you referenced. 

To show the column:
![image](https://user-images.githubusercontent.com/33138761/207668749-b4de6fee-0511-4018-977e-98a46c178856.png)

The result when enabled:
![image](https://user-images.githubusercontent.com/33138761/207669266-a46f80f8-5ff6-4f4f-8b0d-b2d06ed32636.png)

Any additional feedback? Otherwise, will probably merge in next 24 hours.
