### ISSUE TITLE
FEATURE REQUEST: Capability to provide a diff reporting and flagging across STIG versions

### ISSUE THREAD

**Issue by skykam87** [NUWCDIVNPT/stig-manager#885]
DISA periodically updates STIG policies. These updates can include new rules, removal of rules, and updates to existing rules including changes to the severity, discussion, check text or fix text or other reference fields such as CCI mappings. While DISA provides a PDF revision history with each release, the annotations for the updates are generally vague in nature. In order to effectively determine the scope and context of revisions, a labor intensive manual comparison of the updated STIG revision rules with previous STIG revision rules is required. Having the capability to rapidly assess STIG changes would greatly improve the efficiency of this process, and also improve the effectiveness of IA shops leveraging STIG Manager - as STIG updates that do not introduce new rules frequently go unverified without a major trigger point such as a new system evaluations or independent IA V&V. 

Introducing the ability within STIG Manager to **perform differential comparison between two or more STIG revisions** would streamline the manual comparison necessary to evaluate changes and their impacts to asset compliance as DISA makes them available. Capturing this comparison and further adding **automated workflow to flag and enumerate requirements changes affecting individual assets** would allow the user to review applicable STIG rules that are either new, removed or updated since the previous evaluated release would **remove the "assumption of carry-forward compliance"** that comes with simply maintaining previous status from one rule revision to the next when changes are indicated. Per the STIG Manager readme, "_STIG Manager tracks reviews at the Rule ID level, so in most cases a completely reviewed Asset with a new STIG will still have most of the Reviews already populated and in the same state they were in before the update_". If the check or fix context of the rule has changed in a way that impacts the compliance status of the asset, then the system owner may be inaccurately reporting compliance with the carry over of state.

A high level concept could entail this approach:

1. Add an association to the asset for a "last reviewed STIG revision" that would indicate the Version/Release of the STIG that has most recently been reviewed by the asset owner. This association becomes the starting reference point for the STIG diff comparison.
2. Add an association to the asset for the "target STIG revision" that would default to the latest STIG revision of the associated "last reviewed STIG revision", or optionally a user defined STIG revision that is the "last reviewed STIG revision", or a more current STIG revision of the associated "last reviewed STIG revision".
3. Add back end logic to compare "last reviewed STIG revision" fields with "target STIG revision" fields, and flag any differences.
4. For differences flagged, add an indicator to the asset that there has been a change to STIG requirements that necessitates system owner review. This could be handled through a Status workflow, where submitted and accepted results are reset to an Unsubmitted state, potentially with a new status to "Review Rule Revisions".
5. For differences flagged, by default append the following verbiage to the Comment field for an assets STIG evaluation: "Reevaluation required. Previously evaluated as <Evaluation Result value, i.e. NF, O, N/A> based on legacy <STIG Title, Revision #, Version #> which has been modified in a later STIG release."
6. For differences flagged, by default reset the Result to NR after appending the above Comment which captures the previous Result for reference.
7. Allow optional override for Status and Result reset behavior, to maintain previous Status and Result regardless of change. Some teams may not want this behavior. Recommend this option include a warning to the user that potential "False Negatives" in reporting can result in bypassing automated revision history comparison.
8. Add a visual diff window as a fly out button from the Checklist rule view. This button should be present only when a difference is flagged and should show the "last reviewed STIG revision rule" side by side with the "target STIG revision rule" being selected. The differences between each rule should be highlighted for ease of identification to the user.
9. An additional field could be beneficial to add to the target STIG revision rule that allows the user to enter an evaluation summary of the change as a future reference point. "I.e. DISA changed the way this fix is implemented, requiring updates to RHEL8 PAM configurations to comply", or "DISA fixed a typo that does not impact the evaluation status of this rule".
10. It would be beneficial to maintain some record with reporting of STIGs that have been removed for each asset, in the event that the STIG removal necessitates a configuration change to the asset to maintain a least privilege, least footprint approach to security best practices (i.e. the removal of EMET STIG requirements from the Windows STIGs due to Microsoft deprecation of EMET may be a trigger to remove EMET installations and policies from a baseline". Removing STIG rules automatically during a revision update, without maintaining a record of the removal can lead to potentially unnecessary and unjustified configurations deployed and supported within the system owners baseline.

Alternatives to this entail a very manual review of each STIG update, cross referencing with the revision history PDF. In some cases, the DISA revision history is missing some annotations of rule changes which can lead to missed rule changes during a manual review even. The current STIG Viewer tool does not provide a diff capability, and the inconsistent formatting of the DISA XCCDF content presents parsing challenges for typical cybersecurity and sysadmin staff to perform this task consistently and efficiently.

Thanks for your considerations, and your continued contributions to DoD cybersecurity!

**Comment by cd-rite** [comment]
Hi @skykam87 Thank you very much for the suggestion, and for the thought and effort you put into this issue. 
We do have some plans to add a diff report for comparing STIG Revisions, and will use your requests to inform our implementation.

One item I would like to clarify, though, regarding Rule IDs... You mentioned that  _"If the check or fix context of the rule has changed in a way that impacts the compliance status of the asset, then the system owner may be inaccurately reporting compliance with the carry over of state."_ This has absolutely been a concern of ours from the beginning, which is why we attach Reviews to RuleIDs (usually in the form of SV-######r######_rule) atomically, including the "r######" portion...Not the "Group ID" ("V-number") or (aka "STIG Id" aka "Rule_Ver"), which will (sometimes) remain the same even when check content changes. 

In our experience the number after the 'r' in a Rule ID changes with **any** change to the rule content, including changes to the fixes and checks. This is why we associate Reviews to specific Rule IDs, regardless of the STIG Revisions that might contain them. 
If you have examples or info to the contrary, we would love to see it!


We are on break until a few days into the new year, I'll try to respond to a few more of your points when we are back.
Thanks again!

**Comment by csmig** [comment]
The next release of STIG Manager will include an interactive workspace for researching the differences between STIG revisions.

As I developed that feature, it became obvious that `ruleId`s are  very commonly revised *without* a corresponding change to the check content. Even changes to the `<check system>` attribute (essentially a checkId) do not always correspond to content changes. This causes me to rethink our decision to associate assessments with the `ruleId`, which is the pattern we borrowed from XCCDF.

**There is no natural key in the DISA STIG schema that consistently tracks or predicts changes to the check content text.** Therefore, I propose that STIG Manager start associating assessments with a *derived key* based on the message digest of the actual check content. This should significantly increase the number of existing assessments that remain active after updating a STIG revision.

A detail to work out is how the message digest is calculated. It can be done against the literal check text, or against a normalization of the text which removes white space or converts certain characters to a common representation (unicode quotation characters converted to ascii, for example). Any method like this would, of course, not be able to detect when the *semantic* meaning of the check remains the same while the *expression* of the check has changed. That is a more challenging problem which is perhaps best addressed by a natural language AI.

**Comment by cd-rite** [comment]
Hi @skykam87 
Closing this, as our latest releases bring changes that should address several of the points you made in this issue. 
Our latest Release changes the way we track Reviews. Instead of tracking Rule IDs, they now track a key composed of a digest of the Rule's Check content and Version ("STIG Id").   Check out the What's New or the Release Notes and Docs for more detail

Since we track Reviews very granularly, not at the STIG or Checklist level, some of your concerns shouldn't apply

1, 2: Rule ID displayed in "Attributions" indicates which last Rule ID the Review was updated for. Hovering over this indicator shows other Rules that have identical Check Content and STIG Id, and that this Review will apply to. 
3,8: Our STIG Compare tool can show how two versions of the DISA Reference STIGs differ. It displays exactly what changed for each field from Revision to Revision, which should be much more useful than the DISA release info. 
4: If an updated STIG changed the content of a Check,, or introduces new Rules, that Rule will simply be "Unreviewed," which already indicates it needs evaluation.  If a Manager-grant user wants something re-evaluated, they can "Reject" the review. 
5: As a rule, we do not want to alter text or fields that Users store data in. 
6,7. With our new approach, if there is no difference between the check content elements of the requirement, the Review will still apply. Only if there is actual check content change will re-evaluation will be required.
9: Suggest they use the Comment, Detail, or metadata(artifact) fields for this. 

10: Yes, we have considered adding something like an "Asset" History, to show these actions (As well as for Users and Collections) but for now much of that data would only be found in the API logs.  We will track that effort under another issue.

Thanks for the feedback, and let us know if the new Release helps resolve some of these issues!
