### ISSUE TITLE
FEATURE REQUEST: Delegate/assign specific items to owners or specialists over specific assets

### ISSUE THREAD

**Issue by josh-hemphill** [NUWCDIVNPT/stig-manager#895]
**Is your feature request related to a problem? Please describe.**
When specific items in a STIG require contacting or delegating to someone with knowledge of a specific asset, just pointing them to a whole collection/review is impractical, and when those people with just a few items for a few assets need to know what they still need comment on or review, they have to dig through an entire collection for a while just to get back to them.

**Describe the solution you'd like**
It would be nice to have some basic information/tracking around delegation/tasking, at least letting users create some kind of view themselves of just the assets/stigs/items they're actively engaging with.

**Describe alternatives you've considered**
Building a whole separate system to maintain tasking information around the data in the stig-manager.

**Comment by cd-rite** [comment]
HI @josh-hemphill 
Many users use Asset Labels and our view filters for this task. They might assign Assets a label with a persons name, indicating it's their responsibility, or a group or type of Asset, to help groups focus their work.  
Users can also navigate quicker if they filter their views in either the Nav Tree or other workspaces and reports, so that they just see Assets with certain labels.  (The Restricted User Grant will also very narrowly focus what they can see to just what Asset/STIG you assign them. )

Our -latest container (Soon to be released as 1.3.0)  on Docker Hub also includes a switch to our latest Collection Dashboard Navigation approach, which replaces much of the Nav Tree functionality with a Dashboard and Grid panel that also enables those filter features.  

I think between using combinations of Labels and our new Navigation approach, users should be able to get a handle on their responsibilities a bit easier... Let me know if that helps.

**Comment by cd-rite** [comment]
Closing this assuming suggestions fit the need for now.  We are trying to keep features like this generic and flexible, so they can be adapted to various organizations' needs and processes. 
Feel free to reopen or create a new one with additional suggestions.
