### ISSUE TITLE
Break out STIG Rules by severity in metrics endpoints

### ISSUE THREAD

**Issue by cd-rite** [NUWCDIVNPT/stig-manager#983]
Metrics return total STIG Rule count property (as "Assessments"). 
Users have suggested that returning that count broken out by Severity would be helpful for several of their processes.
Something like:
AssessmentsBySeverity{
high: int,
medium: int,
low: int
}

**Comment by vvincevv** [comment]
Hello,

Just curious if this issue would support something I am hoping for.

Currently when looking at the STIGs tabs it shows cumulative CAT# findings for each Benchmark type, but it would be helpful to show instead of cumulative but unique totals. Reasoning being, if we have 100 servers in the collection and they all have the same 2 CAT2's it would currently show 200. In the unique option it would instead just show 2.

Is that what this issue would be able to provide? If not, should I open a separate issue for it?

Thank you for your time and effort!

**Comment by cd-rite** [comment]
I think our Findings report should show you what you are looking for... Accessible here, from the Collection Dashboard:
![image](https://user-images.githubusercontent.com/61710958/234989201-09945ee6-e186-4473-b984-dba67dba03de.png)
This report breaks out the unique Open findings per Rule/Group/CCI in a STIG, and shows how many Assets have that Rule marked Open, with a breakout on the right for all the individual Assets that have it. It's filterable, and can be set to just show specific STIGs:
![image](https://user-images.githubusercontent.com/61710958/234989510-0b001198-abf5-45ed-a171-61098d5ac362.png)

**Comment by cd-rite** [comment]
resolved: #988
