### ISSUE TITLE
STIG Manager Not reading .ckl file correctly.

### ISSUE THREAD

**Issue by livesayjesse** [NUWCDIVNPT/stig-manager#989]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of STIG Manager?

- [X] I am using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases).
- [ ] I am NOT using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases). I am aware that the first thing I will be asked to do is update the application so that I have the latest bugfixes.

### Where are you experiencing the issue?

- [X] API
- [ ] UI or other client
- [ ] Deployment
- [ ] Elsewhere

### Current Behavior

Here is our current setup:

We use Evaluate STIG with SCCM to scan our Windows environment. The checklist is then pushed to our shared drive and pickup up by the STIG Manager Watcher process. The only thing we have updated is Evaluate STIG to make sure we have the latest checks.

In STIG Manager I am seeing systems with partial or all checks being marked as Not Reviewed. When I open the .ckl file on the shared drive it is definitely all Reviewed. In our inspection last year we didn't have these issues so we can only assume it was something with Evaluate STIG.
Here is a sample of one system that is only getting about 50% of the checks correctly:
![image](https://user-images.githubusercontent.com/82839865/235016156-c602d67e-09e9-427a-bb5d-5eaaeb9ac5bc.png)
Here is a sample of the .ckl data for that same system:
![image](https://user-images.githubusercontent.com/82839865/235016317-21182741-47b0-47c1-ae10-a4f16e2cbb3c.png)
And one more very odd part when importing the .ckl manually STIG Manager seems to see everything fine:
![image](https://user-images.githubusercontent.com/82839865/235016469-ef2ba2e6-d65d-4e8e-8a42-9dc58169c7d5.png)

Is there a backend log I could view or some guidance on troubleshooting this?

Additional steps I have tried:
Creating a blank checklist (Windows Server 2019) in STIG Viewer mark all checks as "Not A Finding", saved, and imported.
The result was that STIG Manager worked properly. This also lead us to believe that it might be some way that Evaluate STIG is handeling the saving of the checklist.

Also, this is only happening on about 10-20 percent of systems that we can tell. So its not consistent on each system, STIG checklist, etc.

### Describe your Environment

```markdown
- Hosting:Hosting (1.3.4)
- Browser:Chrome
- OS:Windows 10
- Node:
- npm:
```

**Comment by livesayjesse** [comment]
I think I figured out the issue. So far all of the systems with this issue are .ckl of the previous releases. So I think DISA must have changed things like STIG_UUID, ATTRIBUTE_DATA, or something else in certain checks which STIG Manager doesn't know how to handle (possible). When I open a fresh checklist, import the older checklist data, and re-save I see a sizeable difference in the .ckl file. After comparing the two the data is close, things like Findings details, etc are fine but the differences are all on the identifying features of the STIG rules. 
Not sure if anything can really be done here...lol But I'll leave it up to you all if you want to identify this for improvement. 


Having a view logs feature/tab from the web GUI would be nice to troubleshoot things like this. As a possible outcome.

**Comment by cd-rite** [comment]
Hi @livesayjesse You've pretty much figured it out. STIG Manager **currently** associates Reviews with specific RuleIds, which we have found DISA changes frequently in their releases, without significant content changes.  When you import .ckl files created with older STIG Revisions, they won't always have the exact same set of RuleIds, and so we can't associate those Reviews with the current set.  (If you change your view to look at a STIG Rev that matches the one you imported, you should see all your results).

However, your timing is good! Our next release (1.3.5, targeted for Monday) will introduce a more advanced set of relationships that will match Rules and Reviews using specific Check Content and "version" (often called the STIG ID).  This change will bring a much larger fraction of Reviews forward to the latest STIG Revisions, and only leave Reviews behind that actually change the check requirements for a Rule, and so do not apply to the latest version. 

The API logs are published to STDOUT if you are running the containers, but probably not be useful in this case, since the app is doing exactly what it is intended to do! 
Keep an eye out for the new version that should have the behavior you are looking for!

**Comment by livesayjesse** [comment]
Fantastic news! I had a feeling once i discovered what it was that there wasn't too many ways around it and it was working properly. I will keep an eye out for the new release.

As a long time DoD Contractor this has been an absolute lifesaver! Our ISSM/ISSO is beyond happy with it. All I gotta say is keep up the great work and put in for some raises!
